"""Shared Pydantic schemas for artifacts and domain records."""

from rag_quality_lab.schemas.artifacts import (
    DEFAULT_SCHEMA_VERSION,
    ArtifactIOError,
    ArtifactSchemaVersionError,
    CorpusSummaryArtifact,
    IngestionSummaryArtifact,
    read_json_artifact,
    write_json_artifact,
)
from rag_quality_lab.schemas.corpus import (
    REQUIRED_KNOWLEDGE_CATEGORIES,
    Chunk,
    KnowledgeCategory,
    Provenance,
    Question,
    SourcePage,
    SourceSection,
)
from rag_quality_lab.schemas.eval import (
    REQUIRED_EVALUATION_METRICS,
    EvaluationArtifactPaths,
    EvaluationMetrics,
    EvaluationQuestionResult,
    EvaluationRun,
    GoldenSet,
)
from rag_quality_lab.schemas.trace import (
    AnswerResult,
    CitationValidation,
    ContextBuild,
    ContextChunk,
    ExcludedContextChunk,
    ModelUsage,
    QueryTrace,
    RetrievalResult,
    RouteDecision,
)

__all__ = [
    "REQUIRED_EVALUATION_METRICS",
    "REQUIRED_KNOWLEDGE_CATEGORIES",
    "AnswerResult",
    "ArtifactIOError",
    "ArtifactSchemaVersionError",
    "Chunk",
    "CitationValidation",
    "ContextBuild",
    "ContextChunk",
    "CorpusSummaryArtifact",
    "DEFAULT_SCHEMA_VERSION",
    "EvaluationArtifactPaths",
    "EvaluationMetrics",
    "EvaluationQuestionResult",
    "EvaluationRun",
    "ExcludedContextChunk",
    "GoldenSet",
    "IngestionSummaryArtifact",
    "KnowledgeCategory",
    "ModelUsage",
    "Provenance",
    "QueryTrace",
    "Question",
    "RetrievalResult",
    "RouteDecision",
    "SourcePage",
    "SourceSection",
    "read_json_artifact",
    "write_json_artifact",
]
